version: '3.3'
services:
 mysql:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: 123
   MYSQL_DATABASE: count_my_macros
   MYSQL_USER: admin
   MYSQL_PASSWORD: "123456"
  ports:
   - "9999:3306"


 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   PMA_HOST: mysql
  ports:
   - "8090:80"